FROM python:3.11-slim
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
WORKDIR /app
COPY pyproject.toml .
RUN uv sync --no-dev
COPY frontend/ frontend/
EXPOSE 8002
CMD ["uv","run","streamlit","run","frontend/ui.py","--server.port=8002","--server.address=0.0.0.0"]
